import { prisma } from "@/lib/prisma";
import { ORDER_STATUS } from "@/lib/utils/constants";

/**
 * Creates a PENDING order for a direct "Buy Now" medicine purchase —
 * i.e. one that isn't generated by the subscription scheduler.
 * subscriptionId is left null; totalAmount is computed server-side from
 * the medicine's current price so the client can never send a fake amount.
 */
export async function createDirectOrder({ userId, medicineId, quantity }) {
  const medicine = await prisma.medicine.findUnique({ where: { id: medicineId } });
  if (!medicine) {
    throw new Error("Medicine not found");
  }

  const totalAmount = Number((medicine.price * quantity).toFixed(2));

  return prisma.order.create({
    data: {
      userId,
      subscriptionId: null,
      status: ORDER_STATUS.PENDING,
      totalAmount,
      items: {
        create: [{ medicineId, quantity, price: medicine.price }],
      },
    },
    include: {
      items: { include: { medicine: true } },
    },
  });
}

export async function getOrders(userId) {
  return prisma.order.findMany({
    where: { userId },
    include: {
      items: {
        include: {
          medicine: true,
        },
      },
      subscription: {
        include: {
          medicine: true,
        },
      },
    },
    orderBy: { createdAt: "desc" },
  });
}
