import { prisma } from "@/lib/prisma";
import { ORDER_STATUS } from "@/lib/utils/constants";

/**
 * Creates a PENDING order for a direct "Buy Now" medicine purchase —
 * i.e. one that isn't generated by the subscription scheduler.
 * subscriptionId is left null; totalAmount is computed server-side from
 * the medicine's current price so the client can never send a fake amount.
 */
export async function createDirectOrder({ userId, medicineId, quantity }) {
  const medicine = await prisma.medicine.findUnique({ where: { id: medicineId } });
  if (!medicine) {
    throw new Error("Medicine not found");
  }

  const totalAmount = Number((medicine.price * quantity).toFixed(2));

  return prisma.order.create({
    data: {
      userId,
      subscriptionId: null,
      status: ORDER_STATUS.PENDING,
      totalAmount,
      items: {
        create: [{ medicineId, quantity, price: medicine.price }],
      },
    },
    include: {
      items: { include: { medicine: true } },
    },
  });
}

/**
 * Creates a PENDING order from multiple cart lines at once. Prices are
 * looked up fresh from the DB per medicine, never trusted from the client.
 */
export async function createOrderFromCart({ userId, items }) {
  const medicineIds = items.map((i) => i.medicineId);
  const medicines = await prisma.medicine.findMany({ where: { id: { in: medicineIds } } });

  const medicineMap = new Map(medicines.map((m) => [m.id, m]));

  const orderItems = items.map(({ medicineId, quantity }) => {
    const medicine = medicineMap.get(medicineId);
    if (!medicine) throw new Error(`Medicine ${medicineId} not found`);
    return { medicineId, quantity, price: medicine.price };
  });

  const totalAmount = Number(
    orderItems.reduce((sum, i) => sum + i.price * i.quantity, 0).toFixed(2)
  );

  return prisma.order.create({
    data: {
      userId,
      subscriptionId: null,
      status: ORDER_STATUS.PENDING,
      totalAmount,
      items: { create: orderItems },
    },
    include: {
      items: { include: { medicine: true } },
    },
  });
}

export async function getOrders(userId) {
  return prisma.order.findMany({
    where: { userId },
    include: {
      items: {
        include: {
          medicine: true,
        },
      },
      subscription: {
        include: {
          medicine: true,
        },
      },
    },
    orderBy: { createdAt: "desc" },
  });
}

/**
 * Cancels a PENDING order (one still awaiting/retrying payment) that
 * belongs to the given user. Clears nextPaymentAttemptAt so the scheduler
 * never picks it up for a retry again.
 */
export async function cancelOrder(orderId, userId) {
  const order = await prisma.order.findFirst({
    where: { id: orderId, userId },
  });

  if (!order) {
    throw new Error("Order not found");
  }

  if (order.status !== ORDER_STATUS.PENDING) {
    throw new Error(`Cannot cancel an order that is already ${order.status}`);
  }

  return prisma.order.update({
    where: { id: orderId },
    data: { status: ORDER_STATUS.CANCELLED, nextPaymentAttemptAt: null },
  });
}