name: Docker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./SW2627-NextJS-Cloud-PharmEasy
          file: ./SW2627-NextJS-Cloud-PharmEasy/Dockerfile
          push: false # Verify build only, do not push
          cache-from: type=gha
          cache-to: type=gha,mode=max
